version: '3.3'

services:
  syncthing:
    build:
      context: .
    image: azmo/syncthing
    hostname: ${SYNCTHING_HOSTNAME}
    networks:
      - default
      - traefik_reverseproxy
    environment:
      RUN_UID: ${SYNCTHING_RUN_UID}
      RUN_GID: ${SYNCTHING_RUN_GID}
      SYNCTHING_WEBUI_PORT: ${SYNCTHING_WEBUI_PORT}
      SYNCTHING_WEBUI_ADDRESS: ${SYNCTHING_WEBUI_ADDRESS}
    restart: unless-stopped
    volumes:
      - ${SYNCTHING_HOME_DIRECTORY}:/syncthing
      - ${SYNCTHING_DATA_DIRECTORY}:/syncthing-data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${SYNCTHING_WEBUI_PORT}:8384
    healthcheck:
      test: ${SYNCTHING_HEALTHCHECK}
      interval: '60s'
      retries: 3
      timeout: '30s'
    labels:
      - "traefik.enable=true"
      - "traefik.backend=syncthing"
      - "traefik.frontend.rule=Host:syncthing.zeus.zt.azmo.ninja"
      - "traefik.port=8384"
      - "traefik.frontend.entryPoints=http"
      - "traefik.docker.network=traefik_reverseproxy"
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "20"

networks:
  traefik_reverseproxy:
    external: true
